name: 1 - Hello World Github actions

on:
  push: #git push
     branches:
          - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo 'Hello'        